### ISSUE TITLE
Clearing the genre of the previous song

### ISSUE THREAD

**Issue by zeroma25** [Vexcited/better-spotify-genres#1]
Thanks for fixing and supporting the Spotify Genres extension!
Sometimes, if the current song does not have a genre specified, the genre of the previous song is displayed.
Could you add a function to clear the previous genre before prompting for the genre of the current song?

**Comment by vexcited** [comment]
No problem !

Do you have an example of the songs you play to have this ? So I can reproduce on my side and implement/test it.

Thanks for the report!

**Comment by zeroma25** [comment]
Try running any song with genres and queue this song next:
https://open.spotify.com/track/4s28VI3QU9kRBKY5ssorlP
The genre of the previous song is displayed for me, since genres are not specified for this artist

**Comment by vexcited** [comment]
Those commits should've fixed the issue :

- https://github.com/Vexcited/better-spotify-genres/commit/0cc03547c41ce422aca91335025d6849cd42e5d0
- https://github.com/Vexcited/better-spotify-genres/commit/59e74ba8da4ae3c2a19c6217d2de23e0f1ebf3e8

Please, try to refresh the extension and see if it fixed !

**Comment by zeroma25** [comment]
The genre of the previous song is also displayed, but it should not be there, since this artist does not have a genre specified
![Снимок экрана 2023-12-24 175114](https://github.com/Vexcited/better-spotify-genres/assets/58146362/7b1d900c-fc12-4f71-9b65-4bf3a01cf6f9)
![Снимок экрана 2023-12-24 175140](https://github.com/Vexcited/better-spotify-genres/assets/58146362/ccbedc55-d2db-4385-bace-1a19f76b0d4d)

"Hide Spotify Genres" -> "Show Spotify Genres" helps
![Снимок экрана 2023-12-24 175727](https://github.com/Vexcited/better-spotify-genres/assets/58146362/492a8a4c-f672-4072-97ed-f6f243bcc9cb)

**Comment by vexcited** [comment]
Uhm, it doesn't do it anymore for me ?

Are you sure the extension got updated ?

---

Here's what happens on my end

https://github.com/Vexcited/better-spotify-genres/assets/59152884/597dc76c-eb5b-4996-9bf7-7540bcb6cc17

**Comment by zeroma25** [comment]
For some reason the version from the marketplace didn't work. Installed it manually and it worked.
Thank you!

**Comment by vexcited** [comment]
Incredible ! Yeah for some reason the market isn't up-to-date, it's probably due to the fact they use `jsdelivr` to get the JS script from the repository and their cache takes time before getting updated.

Anyways, thanks you for using `better-spotify-genres` !
