### ISSUE TITLE
CSS Grid template issue in Player

### ISSUE THREAD

**Issue by VPNforWindowsSub** [Vexcited/better-spotify-genres#2]
![image](https://github.com/Vexcited/better-spotify-genres/assets/73077542/d26d7f96-2d15-4726-a6f2-625bda50e251)

**Comment by vexcited** [comment]
Thanks for reporting ! I thought having fixed this but seems like their grid usage is weird.

Will look at it asap!

**Comment by vexcited** [comment]
Strange, it doesn't look to trigger on my side ?

Does it happen only on some kind of condition ?

![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/b9c15ba2-368c-4089-954d-5c5ad0e93581)

**Comment by VPNforWindowsSub** [comment]
I think it's not about the specific song. My guess is that when the song loads a little slower, the genre appears next to the title and artist instead of under it because the genre loaded faster than the actual song. When you quickly click on some song in the list, that may happen. (of course, internet connection speed matters).

https://github.com/Vexcited/better-spotify-genres/assets/73077542/0b7f62cf-f2eb-4cca-b87d-fb5342b5c624

**Comment by vexcited** [comment]
Oh I see ! Let me see if I get that by enabling the network limiter on the DevTools

**Comment by vexcited** [comment]
No matter what I try, I can't seem to replicate hm...

If you're able to open the devtools and see what's happening (or just record a video showing what the DOM nodes look like (with their CSS) in that player), I'd maybe able to figure out a fix.

Thanks, and sorry

**Comment by VPNforWindowsSub** [comment]
I'm not an expert, but take a look and see if this helps. If you need anything else, just let me know, and I'll send it to you.

https://github.com/Vexcited/better-spotify-genres/assets/73077542/674c3160-d7e3-4280-968d-07ae40e9c21b

**Comment by VPNforWindowsSub** [comment]
This is the full DOM node:

[Head.txt](https://github.com/Vexcited/better-spotify-genres/files/13854713/Head.txt)
[Body.txt](https://github.com/Vexcited/better-spotify-genres/files/13854714/Body.txt)
[Page source.txt](https://github.com/Vexcited/better-spotify-genres/files/13854720/Page.source.txt)

**Comment by vexcited** [comment]
As I can see, there's effectively an issue in your DOM.

Let me show you how it should look like :

![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/14377840-d716-411a-865a-ac9a3edb4ea6)

As you can see in my screenshot, the track info container should've this `grid-template` property set up.
For absolutely no reason, it didn't happened on your DOM...

Let me investigate, I guess

**Comment by vexcited** [comment]
Can you record the DevTools on that exact node before the issue happens and then proceed to do the issue with the DevTools opened next to the Spotify window so we can see in real time what's happening.

I think the container gets updated/re-rendered and that makes my `style` property go away (with the grid patch :/)

**Comment by VPNforWindowsSub** [comment]
I just removed it from the marketplace and installed it manually, but I still have that issue.
[Page source 2.txt](https://github.com/Vexcited/better-spotify-genres/files/13854960/Page.source.2.txt)

**Comment by VPNforWindowsSub** [comment]
here is the before and after video:

https://github.com/Vexcited/better-spotify-genres/assets/73077542/4e6c3c1e-e09c-4f41-b700-fca619f519de

**Comment by vexcited** [comment]
I don't know what the hell happened here but now we know exactly why the issue happens 😂  

> I think the container gets updated/re-rendered and that makes my style property go away (with the grid patch :/)

So I was right, now I have to find a workaround for that possibility.

**Comment by vexcited** [comment]
Can you please, retry now ? (using the manual method in case it didn't work to make sure the marketplace isn't outdated)

Just made a new build to fix this specific issue (https://github.com/Vexcited/better-spotify-genres/commit/336f2d597573116bd38482134c3ced9618860094)

**Comment by VPNforWindowsSub** [comment]
Thanks for your efforts; it seems the issue has been resolved.
