### ISSUE TITLE
Not showing genres

### ISSUE THREAD

**Issue by lstres** [Vexcited/better-spotify-genres#4]
The extension isn't working including the original spotify genres, it shows that music icon to toggle genres but it is not showing any genre. Here is a screenshot
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/7a9b0912-9ce8-48e8-919d-456a7b50633a)
and the image when the genres are on
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/d064f9a0-c3f8-43e9-b059-7cb1d51c15d4)
So as you can see the liked button and music button is pushed to side by 10 pixels.
That's the only visual change I can notice

**EDIT:** One more thing, I have this problem for a pretty long time now, but after i reinstalled my windows 11 and downloaded spotify then spicetify. It was working again now it is not. It has been only 2 weeks i guess

**Comment by lstres** [comment]
I have also tried installing it manually, still the same issue

**Comment by matthewyuc** [comment]
same problem

**Comment by vexcited** [comment]
Seems like Spotify changed something in the layout so it just won't appear, I'll look into this this afternoon!

**Comment by lstres** [comment]
Thanks, btw now I can say that I got this bug after updating spotify about 2 days ago

**Comment by vexcited** [comment]
Hm, sadly I can't reproduce it on my Spotify installation on Linux, I tried to upgrade everything but it seems like I don't have anything breaking on my side...

![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/44173ea0-e0eb-4544-a487-f00604c9961a)

If anyone can show what the HTML of the player info container looks like (with devtools), I would be very useful !

**Comment by lstres** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/35c18c56-9fde-4841-9ba1-49402168f9ac)
here is a screenshot, btw you've got a nice desktop setup

**Comment by lstres** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/05f549e8-782e-4147-a11a-318865114a19)
it seems like this thing have to do something with the genres, html isn't my thing lol

**Comment by vexcited** [comment]
Thanks! Well, there's no update in the layout and it in fact works perfectly the way it should...

The only issue is that tags aren't pushed to the `<div ... grid-area: genres ...></div>` that I create manually 🤔 

Is anything showing in the console when you change songs ? Like an error ?

**Comment by lstres** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/8c332b1a-02b0-4452-a683-b8ec1c0cc40b)
changing doesn't give any error, but these are some previous errors

**Comment by vexcited** [comment]
Hm, it's not related sadly...

**Comment by vexcited** [comment]
Let me try to write a custom extension for your case with a bunch of `console.log` everywhere to see where it hangs :sob:

**Comment by lstres** [comment]
that seems like a lot of work ig, no hurry from me. I didn't even notice this but today when I wanted to see the genre of a new song. Thanks for maintaining this extension ❤️

**Comment by vexcited** [comment]
Can you please try with this one and screen whatever shows up in logs ?
https://drive.google.com/file/d/1qjdeTiisyOEoOXHw-oLQ69AXfrepMzY8/view?usp=sharing

Thanks you!

**Comment by lstres** [comment]
can I just replace the genres file in extensions? I actually tried installing it manually.

**Comment by vexcited** [comment]
Yes you should do it that way, and reload the spicetify plugins after

**Comment by lstres** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/79bff27d-ed74-41e2-9775-7d15bc5de761)
here it is

**Comment by lstres** [comment]
this at the last 
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/6ce7a1e5-f6d1-4314-8800-a890cb36d6b9)

**Comment by vexcited** [comment]
Alright, I kinda see what's going on now, let me see what I can do on my end

**Comment by vexcited** [comment]
I would need more info (again) because I don't see why it would fail !
All of the following should be ran in DevTools while on Spotify (when you're playing a song)

1. `Spicetify.Player.data.item.metadata.artist_uri` what's the output ?
  - You should have something looking like this `spotify:artist:xxxxxxxxxxxxxxxxxxxxx`
2. Now save the `xxxxxxxxxxxxxxxxxxxxx` part from 1. and drop it in the following command : `await Spicetify.CosmosAsync.get("https://api.spotify.com/v1/artists/xxxxxxxxxxxxxxxxxxxxx")`, replacing `xxxxxxxxxxxxxxxxxxxxx` by the ID from part 1.

If everything went well you should be able to see `genres` in the output, like this :
![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/a3928887-8543-4936-ac0b-d2ac1ff45e3a)

If all the commands worked well, then this issue is mysterious because that's literally the process I use to have genres in the extension, so if you can do it all by hand there's no reason the extension can't do it !

**Comment by Switchbladd** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/66808884/d009c84a-7463-4adc-ae20-e68f55bef59f)
Same error for any artist & for random symbols too
Artist's page normally opens in browser with same artist url so idk
Edit: spotify info
![image](https://github.com/Vexcited/better-spotify-genres/assets/66808884/60d79318-e52f-4c3a-8547-3cbc2dd7444c)

**Comment by lstres** [comment]
1. The output is 'spotify:artist:7Ln80lUS6He07XvHI8qqHH'
2. I got an error instead of receiving genres:
![image](https://github.com/Vexcited/better-spotify-genres/assets/158139730/56040786-7f04-4474-b8ac-d83f399f8c61)
it was 1 am for me yesterday so I had to sleep that's why pretty late. ig we have a big time difference

**Comment by vexcited** [comment]
Wow ok, so both of you all got this error ... 

Just checked Spicetify issues and found this https://github.com/spicetify/spicetify-cli/issues/1537#issuecomment-1079714623

Feels like I'd need to find a workaround for this case

**Comment by Switchbladd** [comment]
![image](https://github.com/Vexcited/better-spotify-genres/assets/66808884/7ffafcdf-b66e-4ae0-9b6c-32b9c425183b)
https://github.com/spicetify/spicetify-cli/issues/2844 Looks like all CosmosAsync extensions died, so you & we prolly just need to wait for their solution/response
Edit: strange that it works for you, what's your spotify version?

**Comment by vexcited** [comment]
For now, I pushed yesterday a "fix" that uses Last.FM genres instead of Spotify's genres from artists : https://github.com/Vexcited/better-spotify-genres/commit/5e5c3fed51a4341eaf402ae5101ba9c26f490487

The sad thing is that it covers way less songs but works for popular ones.

I'll lookup for an alternative request and will add my solution here if I find one !

In the meantime, use the latest version with Last.FM genres (sorry for the waiting)

**Comment by vexcited** [comment]
> What's your spotify version?

![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/28475c9d-4022-4cc7-aa34-393dcd513044)

Seems like the Linux repository is locked at version 1.2.26.1187 for now : see <http://repository.spotify.com/dists/testing/non-free/binary-amd64/Packages>

That's why I don't have this issue yet, wonder when Spotify will upgrade their repository...

**Comment by lstres** [comment]
so do we need to downgrade?
it will update automatically again 😂

**Comment by vexcited** [comment]
If you do want to have it absolutely working right now, yes downgrading is the only option, but as I said, I'll try to find another alternative to get those genres somehow...

Also, the push I did for using Last.FM genres should work for all versions, so you can still have some genres (if the artist is not unknown :sob:)... You just won't have the Spotify fallback, sadly

(Build for the Last.FM push : <https://github.com/Vexcited/better-spotify-genres/blob/e3dbc344727694c96e841dbd7a97410c9b0de50c/spotifyGenres.js>)

**Comment by lstres** [comment]
thx for the last fm build, i'm sure there will be some other way

**Comment by rxri** [comment]
hiya, `v2.32.0` should fix this issue. It has been resolved by https://github.com/spicetify/spicetify-cli/pull/2846

**Comment by lstres** [comment]
Thanks for telling ❤️

**Comment by vexcited** [comment]
No way ! So everything works like before for you all now ?

If yes, then I'll let the OP close the issue :')

**Comment by lstres** [comment]
for me, it does work like before

**Comment by lstres** [comment]
accidently closed, sorry 😅

**Comment by vexcited** [comment]
I mean, if anybody else don't have the issue anymore too, you can close it !

If someone faces again this issue, they'll probably write it here (so I'll just reopen it) or open a new issue

Thanks !

**Comment by stefb02** [comment]
It works but now it's showing Last FM tags in favour of genres:

![Screenshot 2024-02-21 113549](https://github.com/Vexcited/better-spotify-genres/assets/41242076/dfdac0e0-93d2-462f-8617-09546a3d16bc)

![Screenshot 2024-02-21 113620](https://github.com/Vexcited/better-spotify-genres/assets/41242076/d9e0631e-2327-41ed-b341-3f2cb40f6229)

It seems to only show the genres in the player bar when there's no Last FM tags available.

**Comment by vexcited** [comment]
True! Will revert this behavior in the afternoon, sorry for the inconvenience

**Comment by vexcited** [comment]
@stebo02 done ! Update your extension and it should be back like before.

> Re-implemented in <https://github.com/Vexcited/better-spotify-genres/commit/48dea105b805a8d0b10789f8845efde8246d3465>
