### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by kotudemo** [Vexcited/better-spotify-genres#5]
![image](https://github.com/Vexcited/better-spotify-genres/assets/130310308/e1f06e94-d481-44d9-848b-f3f8f3408502)

**Comment by vexcited** [comment]
Hey ! What's your Spotify and Spicetify version ?

I would need more info, all of the following should be ran in DevTools while on Spotify (when you're playing a song)

1. `Spicetify.Player.data.item.metadata.artist_uri` what's the output ?
  - You should have something looking like this `spotify:artist:xxxxxxxxxxxxxxxxxxxxx`
2. Now save the `xxxxxxxxxxxxxxxxxxxxx` part from 1. and drop it in the following command : `await Spicetify.CosmosAsync.get("https://api.spotify.com/v1/artists/xxxxxxxxxxxxxxxxxxxxx")`, replacing `xxxxxxxxxxxxxxxxxxxxx` by the ID from part 1.

If everything went well you should be able to see `genres` in the output, like this :
![image](https://github.com/Vexcited/better-spotify-genres/assets/59152884/a3928887-8543-4936-ac0b-d2ac1ff45e3a)

What's happening on your end ?

**Comment by vexcited** [comment]
I pushed a new update that fixes https://github.com/Vexcited/better-spotify-genres/issues/7.
Your issue may be related to it, can you please try to update the extension and see if it changes anything ?

**Comment by vexcited** [comment]
Closing as stale. Feel free to reopen if the issue persists on your end.
