### ISSUE TITLE
403 in regions where Spotify does not provide its services

### ISSUE THREAD

**Issue by thatsaylary** [Vexcited/better-spotify-genres#6]
Hi! I've had this problem for a month now I think
![image](https://github.com/Vexcited/better-spotify-genres/assets/106902429/dd35e493-5828-4520-8718-46b8a7c21786)
I just don't have any genres whatsoever. I've seen another bug report about this and have done everything you said and this is the result
![изображение_2024-05-04_143508802](https://github.com/Vexcited/better-spotify-genres/assets/106902429/28ade171-cc70-480e-86bc-3d19d5120430)
pls help :(

**Comment by vexcited** [comment]
Strange behavior, this is kind of an issue on the Spicetify side.

What's your Spotify and Spicetify versions ? I know there was an issue about that at a time but it was fixed on a newer Spicetify version.

**Comment by thatsaylary** [comment]
my spotify version is 1.2.36.959 and my spicetify version is 2.36.10
![image](https://github.com/Vexcited/better-spotify-genres/assets/106902429/5cfce78c-18c0-403f-99ca-229126469330)

**Comment by vexcited** [comment]
I hate it when I can't reproduce it on my end, not sure what to do, you seem to be up to date and there's no issue on Spicetify concerning this...

**Comment by ghost** [comment]
Hello, it seems the extension does not work in regions where Spotify does not provide its services. In Russia it only worked with VPN (For this reason you cannot reproduce it). So I think this is not a bug, it’s just that the Spotify api is not responding.

**Comment by vexcited** [comment]
I pushed a new update that fixes https://github.com/Vexcited/better-spotify-genres/issues/7.
Your issue may be related to it, can you please try to update the extension and see if it changes anything ?

**Comment by ghost** [comment]
No, nothing has changed. I doubt this can be fixed. Figured out how to open the development tools to show you the API response. I made a request `Spicetify.CosmosAsync.get("https://api.spotify.com/v1/artists/6FfjnGXMhxSsJTuGLWBDth")`
![image](https://github.com/Vexcited/better-spotify-genres/assets/63114046/c2c42a30-5c6f-4a42-8fc0-13954596f2a2)
And with VPN
![image](https://github.com/Vexcited/better-spotify-genres/assets/63114046/d9908a3d-faf9-47b5-935f-34bfc9f67c6f)

**Comment by vexcited** [comment]
Since this is an API limitation depending on regions, this issue might won't fix.
