### ISSUE TITLE
Incorrect class name for trackInfo container

### ISSUE THREAD

**Issue by watermelonoof** [Vexcited/better-spotify-genres#7]
I just installed the extension and noticed it does not add track genre below artist name, so I tried to inspect the dom and noticed the class name of that container is now `.main-nowPlayingWidget-trackInfo`. It seemed to work after I did a replace all occurrence of `.main-trackInfo-container` to `.main-nowPlayingWidget-trackInfo`. I dunno know if this is the case for anyone else tho.

![image](https://github.com/Vexcited/better-spotify-genres/assets/68735408/1bd7f1b3-ada6-499a-8ab2-35e928de97b7)

**Comment by vexcited** [comment]
That's interesting, sadly I still have the old class name on the latest Spotify version.

I will try to add a support for both class names then, I'm not home right now, will probably do it in a few hours.

**Comment by watermelonoof** [comment]
Forgot to mention here's my version info

Spotify for Windows (32 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Theme: Ziro / rose-pine
Extensions: popupLyrics.js, spotifyGenres.js, shuffle+.js, bookmark.js, loopyLoop.js, fullAlbumDate.js, oneko.js, cat-jam.js, songstats.js, volumePercentage.js
Custom apps: marketplace, lyrics-plus
xpui_2024-05-17_1715913620018_a4a70a0
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake

One more thing, I'm not sure if using SpotX has anything to do with this.

**Comment by vexcited** [comment]
Hey! Can you please try with the new release ?

Here's the bundle file if you can't upgrade yet through the marketplace : https://github.com/Vexcited/better-spotify-genres/blob/build/spotifyGenres.js

**Comment by watermelonoof** [comment]
Yep works perfectly, thanks for the quick fix!
