### ISSUE TITLE
[Feature] Option to hide or move the button

### ISSUE THREAD

**Issue by bgiesing** [Vexcited/better-spotify-genres#8]
I currently use multiple extensions that put icons on the left side there and most notably, Star Ratings, which takes up a load of space so I can barely even see the song name anymore.

It would help greatly if I could hide the icon or move it to the less cluttered right side, the profile menu, or somewhere else since I basically have no intention of ever toggling it off so it’s kinda useless and just wasting space.

**Comment by vexcited** [comment]
Great idea ! I'll take a look and see if there's any way to put the toggle in the user settings.

**Comment by Xelvoren** [comment]
+1

**Comment by vexcited** [comment]
I think I'm going to completely remove this button for a simple reason :

- If you install the plugin, it's because you need
- If you don't need it anymore, you just disable the plugin

It makes much more sense to me, I guess.
I also start to hate that button, lol

**Comment by Xelvoren** [comment]
Thank you so much!! I can't believe you already did it in a day. Appreciate your work!
